name: BarleyTeaAPI
version: 1.0.0
description: a custom mob/item/block API for Paper-based server software
author: new1271 (RiceTeaInMC)
main: org.ricetea.barleyteaapi.BarleyTeaAPI
api-version: 1.20
depend:
  - "ProtocolLib"
softdepend:
  - "ExcellentEnchants"
