name: BarleyTeaAPI
version: 1.0.0
description: a mob/item API for Paper server software
author: new1271 (RiceTeaInMC)
main: org.ricetea.barleyteaapi.BarleyTeaAPI
api-version: 1.20
softdepend:
  - "ExcellentEnchants"
